-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."MooLey"
(
)
;

BEGIN;

CREATE TABLE IF NOT EXISTS public.jogador
(
    id integer NOT NULL,
    nome character varying NOT NULL,
    altura integer NOT NULL,
    posicao character varying NOT NULL,
    idade integer NOT NULL,
    envergadura integer NOT NULL,
    al_ver integer NOT NULL,
    CONSTRAINT pk_jogador PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sequencia_treino
(
    id integer NOT NULL,
    dia date NOT NULL,
    tipo character varying NOT NULL,
    treino character varying NOT NULL,
    CONSTRAINT pk_sequencia_treino PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.treina
(
    jogador_id integer NOT NULL,
    sequencia_treino_id integer NOT NULL,
    CONSTRAINT pk_treina PRIMARY KEY (jogador_id, sequencia_treino_id),
    CONSTRAINT fk_treina_jogador FOREIGN KEY (jogador_id) 
        REFERENCES public.jogador (id) ON DELETE CASCADE,
    CONSTRAINT fk_treina_sequencia FOREIGN KEY (sequencia_treino_id) 
        REFERENCES public.sequencia_treino (id) ON DELETE CASCADE
);

END;

ALTER TABLE IF EXISTS public.treina
    ADD FOREIGN KEY (jogador_id)
    REFERENCES public.jogador (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.treina
    ADD FOREIGN KEY (sequencia_treino_id)
    REFERENCES public.sequencia_treino (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

ALTER TABLE public.sequencia_treino 
    ALTER COLUMN dia TYPE character varying(50) USING dia::character varying;

	ALTER TABLE public.jogador 
    ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

INSERT INTO public.jogador (id, nome, altura, posicao, idade, envergadura, al_ver)
VALUES 
    (1, 'LeBron James', 206, 'Ala', 39, 214, 289),
    (2, 'Stephen Curry', 188, 'Armador', 36, 192, 246),
    (3, 'Giannis Antetokounmpo', 211, 'Ala-Pivô', 29, 221, 292);

INSERT INTO public.sequencia_treino (id, dia, tipo, treino)
VALUES 
    (1, 'Domingo', 'salte+', '1 Agachamentos'),
    (2, 'Segunda', 'salte+', '10 Agachamentos'),
    (3, 'Terca', 'salte+', '100 Agachamentos'),
    (4, 'Quarta', 'salte+', '1000 Agachamentos'),
    (5, 'Quinta', 'salte+', '10000 Agachamentos'),
    (6, 'Sexta', 'salte+', '100000 Agachamentos'),
    (7, 'Sabado', 'salte+', '1000000 Agachamentos'),
    (8, 'Domingo', 'ataque+', '1 ataques'),
    (9, 'Segunda', 'ataque+', '10 ataques'),
    (10, 'Terca', 'ataque+', '100 ataques'),
    (11, 'Quarta', 'ataque+', '1000 ataques'),
    (12, 'Quinta', 'ataque+', '10000 ataques'),
    (13, 'Sexta', 'ataque+', '100000 ataques'),
    (14, 'Sabado', 'ataque+', '1000000 ataques'),
    (15, 'Domingo', 'defenda+', '1 manchete'),
    (16, 'Segunda', 'defenda+', '10 manchete'),
    (17, 'Terca', 'defenda+', '100 manchete'),
    (18, 'Quarta', 'defenda+', '1000 manchete'),
    (19, 'Quinta', 'defenda+', '10000 manchete'),
    (20, 'Sexta', 'defenda+', '100000 manchete'),
    (21, 'Sabado', 'defenda+', '1000000 manchete');
	
SELECT * FROM public.sequencia_treino